<a href="https://colab.research.google.com/github/hend-22/-IT326-Project/blob/main/Reports/Phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Daily Stress Level Prediction Using Wearable and Lifestyle Data

## Project Goal
The goal of this project is to apply classification and clustering techniques to wearable and lifestyle data. Classification will be used to predict the Daily_Stress_Level as Low, Medium, or High, while clustering will be used to identify groups with similar characteristics.

## Dataset Source

Source: Kaggle  
URL: https://www.kaggle.com/datasets/itzzomkar/wearable-tech-sleep-quality-and-stress/data

## Dataset Description

**Number of instances:** 10000

**Number of attributes:** 16

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Raw_Dataset.csv')
df.shape

(10000, 16)

**Features :**

Data types and numbers of the attirubtes.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   User_ID                  10000 non-null  object
 1   Age                      10000 non-null  int64
 2   Gender                   10000 non-null  object
 3   Physical_Activity_Level  10000 non-null  object
 4   Diet_Type                10000 non-null  object
 5   BMI                      9790 non-null   float64
 6   Caffeine_Intake_mg       9794 non-null   float64
 7   Water_Intake_liters      10000 non-null  float64
 8   Screen_Time_Hours        10000 non-null  float64
 9   Daily_Steps              10000 non-null  int64
 10  Calories_Burned          10000 non-null  int64
 11  Resting_Heart_Rate       9781 non-null   float64
 12  Daily_Sleep_Hours        9810 non-null   float64
 13  Deep_Sleep_Hours         10000 non-null  float64
 14  Sleep_Quality_Score      10000 non-null  float64
 15  Daily_Stress_Level       10000 non-null  object
dtypes: float64(8), int64(3), object(5)
memory usage: 1.2+ MB

**Class attribute:** Daily_Stress_Level

 **Class values:**
  - Low: 5,789
  - Medium: 3,786
  - High: 425

In [ ]:
df['Daily_Stress_Level'].value_counts()

Daily_Stress_Level
Low       5789
Medium    3786
High       425
Name: count, dtype: int64

**Dataset Sample**

To print a small sample of the raw dataset to show how the data looks.

In [ ]:
df.head()

,User_ID,Age,Gender,Physical_Activity_Level,Diet_Type,BMI,Caffeine_Intake_mg,Water_Intake_liters,Screen_Time_Hours,Daily_Steps,Calories_Burned,Resting_Heart_Rate,Daily_Sleep_Hours,Deep_Sleep_Hours,Sleep_Quality_Score,Daily_Stress_Level
0,U00001,56,Female,Low,Healthy,25.1,99.0,1.6,3.9,4731,1697,74.0,6.6,1.5,4.0,Low
1,U00002,69,Male,Low,Average,25.8,104.0,2.2,3.9,4440,1377,70.0,8.0,2.4,5.3,Low
2,U00003,46,Male,Low,Average,24.0,188.0,1.4,5.5,5023,1289,72.0,8.2,1.9,5.0,Medium
3,U00004,32,Female,Medium,Healthy,25.5,124.0,3.1,9.8,6082,1683,69.0,7.4,2.5,3.9,Low
4,U00005,60,Male,Medium,Unhealthy,NaN,0.0,2.4,5.3,7285,1621,73.0,7.9,2.2,5.2,Low

# Dataset Summary
- Number of instances: 10,000
- Number of attributes: 16
- Data types: 8 float, 3 integer, and 5 object attributes
- Class attribute: Daily_Stress_Level
- Class values:
  - Low: 5,789
  - Medium: 3,786
  - High: 425